version: '3'

services: 
  django_covid:
    build: .
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    image: django_covid:latest
    container_name: django_container
    command: bash -c "python manage.py runserver 0.0.0.0:8000"