# Generated by Django 2.2 on 2021-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField(default=0)),
                ('result', models.BooleanField()),
                ('audio_path', models.CharField(max_length=100)),
            ],
        ),
    ]
