# Generated by Django 2.2 on 2021-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(choices=[('nam', 'Nam'), ('nữ', 'Nữ')], default='Nam', max_length=5),
        ),
    ]
