# Generated by Django 2.2 on 2021-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210801_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='audio_path',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
