# Generated by Django 2.2 on 2021-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210801_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='audio_path',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='result',
            field=models.NullBooleanField(default=False),
        ),
    ]
