# Generated by Django 2.2 on 2021-08-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210801_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
