# Generated by Django 2.2 on 2021-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210801_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
