# Generated by Django 2.2 on 2021-08-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyform_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyForm',
            new_name='Survey',
        ),
    ]
